// Code generated by "enumer -type=Position -json -text -yaml -values -trimprefix=Position -output=gen_position_enumer.go"; DO NOT EDIT.

package data

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PositionName = "UnknownTopJungleMidBotSupportTeam"

var _PositionIndex = [...]uint8{0, 7, 10, 16, 19, 22, 29, 33}

const _PositionLowerName = "unknowntopjunglemidbotsupportteam"

func (i Position) String() string {
	if i < 0 || i >= Position(len(_PositionIndex)-1) {
		return fmt.Sprintf("Position(%d)", i)
	}
	return _PositionName[_PositionIndex[i]:_PositionIndex[i+1]]
}

func (Position) Values() []string {
	return PositionStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PositionNoOp() {
	var x [1]struct{}
	_ = x[PositionUnknown-(0)]
	_ = x[PositionTop-(1)]
	_ = x[PositionJungle-(2)]
	_ = x[PositionMid-(3)]
	_ = x[PositionBot-(4)]
	_ = x[PositionSupport-(5)]
	_ = x[PositionTeam-(6)]
}

var _PositionValues = []Position{PositionUnknown, PositionTop, PositionJungle, PositionMid, PositionBot, PositionSupport, PositionTeam}

var _PositionNameToValueMap = map[string]Position{
	_PositionName[0:7]:        PositionUnknown,
	_PositionLowerName[0:7]:   PositionUnknown,
	_PositionName[7:10]:       PositionTop,
	_PositionLowerName[7:10]:  PositionTop,
	_PositionName[10:16]:      PositionJungle,
	_PositionLowerName[10:16]: PositionJungle,
	_PositionName[16:19]:      PositionMid,
	_PositionLowerName[16:19]: PositionMid,
	_PositionName[19:22]:      PositionBot,
	_PositionLowerName[19:22]: PositionBot,
	_PositionName[22:29]:      PositionSupport,
	_PositionLowerName[22:29]: PositionSupport,
	_PositionName[29:33]:      PositionTeam,
	_PositionLowerName[29:33]: PositionTeam,
}

var _PositionNames = []string{
	_PositionName[0:7],
	_PositionName[7:10],
	_PositionName[10:16],
	_PositionName[16:19],
	_PositionName[19:22],
	_PositionName[22:29],
	_PositionName[29:33],
}

// PositionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PositionString(s string) (Position, error) {
	if val, ok := _PositionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PositionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Position values", s)
}

// PositionValues returns all values of the enum
func PositionValues() []Position {
	return _PositionValues
}

// PositionStrings returns a slice of all String values of the enum
func PositionStrings() []string {
	strs := make([]string, len(_PositionNames))
	copy(strs, _PositionNames)
	return strs
}

// IsAPosition returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Position) IsAPosition() bool {
	for _, v := range _PositionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Position
func (i Position) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Position
func (i *Position) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Position should be a string, got %s", data)
	}

	var err error
	*i, err = PositionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Position
func (i Position) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Position
func (i *Position) UnmarshalText(text []byte) error {
	var err error
	*i, err = PositionString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Position
func (i Position) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Position
func (i *Position) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = PositionString(s)
	return err
}
