// Code generated by "enumer -type=RankTier -json -text -yaml -values -output=gen_ranktier_enumer.go"; DO NOT EDIT.

package data

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _RankTierName = "RankUnknownRankUnrankedIron_4Iron_3Iron_2Iron_1Bronze_4Bronze_3Bronze_2Bronze_1Silver_4Silver_3Silver_2Silver_1Gold_4Gold_3Gold_2Gold_1Platinum_4Platinum_3Platinum_2Platinum_1Emerald_4Emerald_3Emerald_2Emerald_1Diamond_4Diamond_3Diamond_2Diamond_1MasterGrandMasterChallenger"

var _RankTierIndex = [...]uint16{0, 11, 23, 29, 35, 41, 47, 55, 63, 71, 79, 87, 95, 103, 111, 117, 123, 129, 135, 145, 155, 165, 175, 184, 193, 202, 211, 220, 229, 238, 247, 253, 264, 274}

const _RankTierLowerName = "rankunknownrankunrankediron_4iron_3iron_2iron_1bronze_4bronze_3bronze_2bronze_1silver_4silver_3silver_2silver_1gold_4gold_3gold_2gold_1platinum_4platinum_3platinum_2platinum_1emerald_4emerald_3emerald_2emerald_1diamond_4diamond_3diamond_2diamond_1mastergrandmasterchallenger"

func (i RankTier) String() string {
	if i < 0 || i >= RankTier(len(_RankTierIndex)-1) {
		return fmt.Sprintf("RankTier(%d)", i)
	}
	return _RankTierName[_RankTierIndex[i]:_RankTierIndex[i+1]]
}

func (RankTier) Values() []string {
	return RankTierStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RankTierNoOp() {
	var x [1]struct{}
	_ = x[RankUnknown-(0)]
	_ = x[RankUnranked-(1)]
	_ = x[Iron_4-(2)]
	_ = x[Iron_3-(3)]
	_ = x[Iron_2-(4)]
	_ = x[Iron_1-(5)]
	_ = x[Bronze_4-(6)]
	_ = x[Bronze_3-(7)]
	_ = x[Bronze_2-(8)]
	_ = x[Bronze_1-(9)]
	_ = x[Silver_4-(10)]
	_ = x[Silver_3-(11)]
	_ = x[Silver_2-(12)]
	_ = x[Silver_1-(13)]
	_ = x[Gold_4-(14)]
	_ = x[Gold_3-(15)]
	_ = x[Gold_2-(16)]
	_ = x[Gold_1-(17)]
	_ = x[Platinum_4-(18)]
	_ = x[Platinum_3-(19)]
	_ = x[Platinum_2-(20)]
	_ = x[Platinum_1-(21)]
	_ = x[Emerald_4-(22)]
	_ = x[Emerald_3-(23)]
	_ = x[Emerald_2-(24)]
	_ = x[Emerald_1-(25)]
	_ = x[Diamond_4-(26)]
	_ = x[Diamond_3-(27)]
	_ = x[Diamond_2-(28)]
	_ = x[Diamond_1-(29)]
	_ = x[Master-(30)]
	_ = x[GrandMaster-(31)]
	_ = x[Challenger-(32)]
}

var _RankTierValues = []RankTier{RankUnknown, RankUnranked, Iron_4, Iron_3, Iron_2, Iron_1, Bronze_4, Bronze_3, Bronze_2, Bronze_1, Silver_4, Silver_3, Silver_2, Silver_1, Gold_4, Gold_3, Gold_2, Gold_1, Platinum_4, Platinum_3, Platinum_2, Platinum_1, Emerald_4, Emerald_3, Emerald_2, Emerald_1, Diamond_4, Diamond_3, Diamond_2, Diamond_1, Master, GrandMaster, Challenger}

var _RankTierNameToValueMap = map[string]RankTier{
	_RankTierName[0:11]:         RankUnknown,
	_RankTierLowerName[0:11]:    RankUnknown,
	_RankTierName[11:23]:        RankUnranked,
	_RankTierLowerName[11:23]:   RankUnranked,
	_RankTierName[23:29]:        Iron_4,
	_RankTierLowerName[23:29]:   Iron_4,
	_RankTierName[29:35]:        Iron_3,
	_RankTierLowerName[29:35]:   Iron_3,
	_RankTierName[35:41]:        Iron_2,
	_RankTierLowerName[35:41]:   Iron_2,
	_RankTierName[41:47]:        Iron_1,
	_RankTierLowerName[41:47]:   Iron_1,
	_RankTierName[47:55]:        Bronze_4,
	_RankTierLowerName[47:55]:   Bronze_4,
	_RankTierName[55:63]:        Bronze_3,
	_RankTierLowerName[55:63]:   Bronze_3,
	_RankTierName[63:71]:        Bronze_2,
	_RankTierLowerName[63:71]:   Bronze_2,
	_RankTierName[71:79]:        Bronze_1,
	_RankTierLowerName[71:79]:   Bronze_1,
	_RankTierName[79:87]:        Silver_4,
	_RankTierLowerName[79:87]:   Silver_4,
	_RankTierName[87:95]:        Silver_3,
	_RankTierLowerName[87:95]:   Silver_3,
	_RankTierName[95:103]:       Silver_2,
	_RankTierLowerName[95:103]:  Silver_2,
	_RankTierName[103:111]:      Silver_1,
	_RankTierLowerName[103:111]: Silver_1,
	_RankTierName[111:117]:      Gold_4,
	_RankTierLowerName[111:117]: Gold_4,
	_RankTierName[117:123]:      Gold_3,
	_RankTierLowerName[117:123]: Gold_3,
	_RankTierName[123:129]:      Gold_2,
	_RankTierLowerName[123:129]: Gold_2,
	_RankTierName[129:135]:      Gold_1,
	_RankTierLowerName[129:135]: Gold_1,
	_RankTierName[135:145]:      Platinum_4,
	_RankTierLowerName[135:145]: Platinum_4,
	_RankTierName[145:155]:      Platinum_3,
	_RankTierLowerName[145:155]: Platinum_3,
	_RankTierName[155:165]:      Platinum_2,
	_RankTierLowerName[155:165]: Platinum_2,
	_RankTierName[165:175]:      Platinum_1,
	_RankTierLowerName[165:175]: Platinum_1,
	_RankTierName[175:184]:      Emerald_4,
	_RankTierLowerName[175:184]: Emerald_4,
	_RankTierName[184:193]:      Emerald_3,
	_RankTierLowerName[184:193]: Emerald_3,
	_RankTierName[193:202]:      Emerald_2,
	_RankTierLowerName[193:202]: Emerald_2,
	_RankTierName[202:211]:      Emerald_1,
	_RankTierLowerName[202:211]: Emerald_1,
	_RankTierName[211:220]:      Diamond_4,
	_RankTierLowerName[211:220]: Diamond_4,
	_RankTierName[220:229]:      Diamond_3,
	_RankTierLowerName[220:229]: Diamond_3,
	_RankTierName[229:238]:      Diamond_2,
	_RankTierLowerName[229:238]: Diamond_2,
	_RankTierName[238:247]:      Diamond_1,
	_RankTierLowerName[238:247]: Diamond_1,
	_RankTierName[247:253]:      Master,
	_RankTierLowerName[247:253]: Master,
	_RankTierName[253:264]:      GrandMaster,
	_RankTierLowerName[253:264]: GrandMaster,
	_RankTierName[264:274]:      Challenger,
	_RankTierLowerName[264:274]: Challenger,
}

var _RankTierNames = []string{
	_RankTierName[0:11],
	_RankTierName[11:23],
	_RankTierName[23:29],
	_RankTierName[29:35],
	_RankTierName[35:41],
	_RankTierName[41:47],
	_RankTierName[47:55],
	_RankTierName[55:63],
	_RankTierName[63:71],
	_RankTierName[71:79],
	_RankTierName[79:87],
	_RankTierName[87:95],
	_RankTierName[95:103],
	_RankTierName[103:111],
	_RankTierName[111:117],
	_RankTierName[117:123],
	_RankTierName[123:129],
	_RankTierName[129:135],
	_RankTierName[135:145],
	_RankTierName[145:155],
	_RankTierName[155:165],
	_RankTierName[165:175],
	_RankTierName[175:184],
	_RankTierName[184:193],
	_RankTierName[193:202],
	_RankTierName[202:211],
	_RankTierName[211:220],
	_RankTierName[220:229],
	_RankTierName[229:238],
	_RankTierName[238:247],
	_RankTierName[247:253],
	_RankTierName[253:264],
	_RankTierName[264:274],
}

// RankTierString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RankTierString(s string) (RankTier, error) {
	if val, ok := _RankTierNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RankTierNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RankTier values", s)
}

// RankTierValues returns all values of the enum
func RankTierValues() []RankTier {
	return _RankTierValues
}

// RankTierStrings returns a slice of all String values of the enum
func RankTierStrings() []string {
	strs := make([]string, len(_RankTierNames))
	copy(strs, _RankTierNames)
	return strs
}

// IsARankTier returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RankTier) IsARankTier() bool {
	for _, v := range _RankTierValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RankTier
func (i RankTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RankTier
func (i *RankTier) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RankTier should be a string, got %s", data)
	}

	var err error
	*i, err = RankTierString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for RankTier
func (i RankTier) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for RankTier
func (i *RankTier) UnmarshalText(text []byte) error {
	var err error
	*i, err = RankTierString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for RankTier
func (i RankTier) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for RankTier
func (i *RankTier) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = RankTierString(s)
	return err
}
