// Code generated by "enumer -type=DragonType -json -text -yaml -values -trimprefix=DragonType -output=gen_dragontype_enumer.go"; DO NOT EDIT.

package data

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DragonTypeName = "UnknownInfernalMountainOceanCloudHextechChemtechElder"

var _DragonTypeIndex = [...]uint8{0, 7, 15, 23, 28, 33, 40, 48, 53}

const _DragonTypeLowerName = "unknowninfernalmountainoceancloudhextechchemtechelder"

func (i DragonType) String() string {
	if i < 0 || i >= DragonType(len(_DragonTypeIndex)-1) {
		return fmt.Sprintf("DragonType(%d)", i)
	}
	return _DragonTypeName[_DragonTypeIndex[i]:_DragonTypeIndex[i+1]]
}

func (DragonType) Values() []string {
	return DragonTypeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DragonTypeNoOp() {
	var x [1]struct{}
	_ = x[DragonTypeUnknown-(0)]
	_ = x[DragonTypeInfernal-(1)]
	_ = x[DragonTypeMountain-(2)]
	_ = x[DragonTypeOcean-(3)]
	_ = x[DragonTypeCloud-(4)]
	_ = x[DragonTypeHextech-(5)]
	_ = x[DragonTypeChemtech-(6)]
	_ = x[DragonTypeElder-(7)]
}

var _DragonTypeValues = []DragonType{DragonTypeUnknown, DragonTypeInfernal, DragonTypeMountain, DragonTypeOcean, DragonTypeCloud, DragonTypeHextech, DragonTypeChemtech, DragonTypeElder}

var _DragonTypeNameToValueMap = map[string]DragonType{
	_DragonTypeName[0:7]:        DragonTypeUnknown,
	_DragonTypeLowerName[0:7]:   DragonTypeUnknown,
	_DragonTypeName[7:15]:       DragonTypeInfernal,
	_DragonTypeLowerName[7:15]:  DragonTypeInfernal,
	_DragonTypeName[15:23]:      DragonTypeMountain,
	_DragonTypeLowerName[15:23]: DragonTypeMountain,
	_DragonTypeName[23:28]:      DragonTypeOcean,
	_DragonTypeLowerName[23:28]: DragonTypeOcean,
	_DragonTypeName[28:33]:      DragonTypeCloud,
	_DragonTypeLowerName[28:33]: DragonTypeCloud,
	_DragonTypeName[33:40]:      DragonTypeHextech,
	_DragonTypeLowerName[33:40]: DragonTypeHextech,
	_DragonTypeName[40:48]:      DragonTypeChemtech,
	_DragonTypeLowerName[40:48]: DragonTypeChemtech,
	_DragonTypeName[48:53]:      DragonTypeElder,
	_DragonTypeLowerName[48:53]: DragonTypeElder,
}

var _DragonTypeNames = []string{
	_DragonTypeName[0:7],
	_DragonTypeName[7:15],
	_DragonTypeName[15:23],
	_DragonTypeName[23:28],
	_DragonTypeName[28:33],
	_DragonTypeName[33:40],
	_DragonTypeName[40:48],
	_DragonTypeName[48:53],
}

// DragonTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DragonTypeString(s string) (DragonType, error) {
	if val, ok := _DragonTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DragonTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DragonType values", s)
}

// DragonTypeValues returns all values of the enum
func DragonTypeValues() []DragonType {
	return _DragonTypeValues
}

// DragonTypeStrings returns a slice of all String values of the enum
func DragonTypeStrings() []string {
	strs := make([]string, len(_DragonTypeNames))
	copy(strs, _DragonTypeNames)
	return strs
}

// IsADragonType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DragonType) IsADragonType() bool {
	for _, v := range _DragonTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DragonType
func (i DragonType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DragonType
func (i *DragonType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DragonType should be a string, got %s", data)
	}

	var err error
	*i, err = DragonTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DragonType
func (i DragonType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DragonType
func (i *DragonType) UnmarshalText(text []byte) error {
	var err error
	*i, err = DragonTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for DragonType
func (i DragonType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for DragonType
func (i *DragonType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = DragonTypeString(s)
	return err
}
