// Code generated by "enumer -type=DataCompleteness -json -text -yaml -values -trimprefix=DataCompleteness -output=gen_datacompleteness_enumer.go"; DO NOT EDIT.

package data

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DataCompletenessName = "UnknownCompletePartial"

var _DataCompletenessIndex = [...]uint8{0, 7, 15, 22}

const _DataCompletenessLowerName = "unknowncompletepartial"

func (i DataCompleteness) String() string {
	if i < 0 || i >= DataCompleteness(len(_DataCompletenessIndex)-1) {
		return fmt.Sprintf("DataCompleteness(%d)", i)
	}
	return _DataCompletenessName[_DataCompletenessIndex[i]:_DataCompletenessIndex[i+1]]
}

func (DataCompleteness) Values() []string {
	return DataCompletenessStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DataCompletenessNoOp() {
	var x [1]struct{}
	_ = x[DataCompletenessUnknown-(0)]
	_ = x[DataCompletenessComplete-(1)]
	_ = x[DataCompletenessPartial-(2)]
}

var _DataCompletenessValues = []DataCompleteness{DataCompletenessUnknown, DataCompletenessComplete, DataCompletenessPartial}

var _DataCompletenessNameToValueMap = map[string]DataCompleteness{
	_DataCompletenessName[0:7]:        DataCompletenessUnknown,
	_DataCompletenessLowerName[0:7]:   DataCompletenessUnknown,
	_DataCompletenessName[7:15]:       DataCompletenessComplete,
	_DataCompletenessLowerName[7:15]:  DataCompletenessComplete,
	_DataCompletenessName[15:22]:      DataCompletenessPartial,
	_DataCompletenessLowerName[15:22]: DataCompletenessPartial,
}

var _DataCompletenessNames = []string{
	_DataCompletenessName[0:7],
	_DataCompletenessName[7:15],
	_DataCompletenessName[15:22],
}

// DataCompletenessString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DataCompletenessString(s string) (DataCompleteness, error) {
	if val, ok := _DataCompletenessNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DataCompletenessNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DataCompleteness values", s)
}

// DataCompletenessValues returns all values of the enum
func DataCompletenessValues() []DataCompleteness {
	return _DataCompletenessValues
}

// DataCompletenessStrings returns a slice of all String values of the enum
func DataCompletenessStrings() []string {
	strs := make([]string, len(_DataCompletenessNames))
	copy(strs, _DataCompletenessNames)
	return strs
}

// IsADataCompleteness returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DataCompleteness) IsADataCompleteness() bool {
	for _, v := range _DataCompletenessValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DataCompleteness
func (i DataCompleteness) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DataCompleteness
func (i *DataCompleteness) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DataCompleteness should be a string, got %s", data)
	}

	var err error
	*i, err = DataCompletenessString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for DataCompleteness
func (i DataCompleteness) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DataCompleteness
func (i *DataCompleteness) UnmarshalText(text []byte) error {
	var err error
	*i, err = DataCompletenessString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for DataCompleteness
func (i DataCompleteness) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for DataCompleteness
func (i *DataCompleteness) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = DataCompletenessString(s)
	return err
}
