// Code generated by "enumer -type=Side -json -text -yaml -values -trimprefix=Side -output=gen_side_enumer.go"; DO NOT EDIT.

package data

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SideName = "UnknownBlueRed"

var _SideIndex = [...]uint8{0, 7, 11, 14}

const _SideLowerName = "unknownbluered"

func (i Side) String() string {
	if i < 0 || i >= Side(len(_SideIndex)-1) {
		return fmt.Sprintf("Side(%d)", i)
	}
	return _SideName[_SideIndex[i]:_SideIndex[i+1]]
}

func (Side) Values() []string {
	return SideStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SideNoOp() {
	var x [1]struct{}
	_ = x[SideUnknown-(0)]
	_ = x[SideBlue-(1)]
	_ = x[SideRed-(2)]
}

var _SideValues = []Side{SideUnknown, SideBlue, SideRed}

var _SideNameToValueMap = map[string]Side{
	_SideName[0:7]:        SideUnknown,
	_SideLowerName[0:7]:   SideUnknown,
	_SideName[7:11]:       SideBlue,
	_SideLowerName[7:11]:  SideBlue,
	_SideName[11:14]:      SideRed,
	_SideLowerName[11:14]: SideRed,
}

var _SideNames = []string{
	_SideName[0:7],
	_SideName[7:11],
	_SideName[11:14],
}

// SideString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SideString(s string) (Side, error) {
	if val, ok := _SideNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SideNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Side values", s)
}

// SideValues returns all values of the enum
func SideValues() []Side {
	return _SideValues
}

// SideStrings returns a slice of all String values of the enum
func SideStrings() []string {
	strs := make([]string, len(_SideNames))
	copy(strs, _SideNames)
	return strs
}

// IsASide returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Side) IsASide() bool {
	for _, v := range _SideValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Side
func (i Side) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Side
func (i *Side) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Side should be a string, got %s", data)
	}

	var err error
	*i, err = SideString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Side
func (i Side) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Side
func (i *Side) UnmarshalText(text []byte) error {
	var err error
	*i, err = SideString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for Side
func (i Side) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Side
func (i *Side) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = SideString(s)
	return err
}
